version: '3'

services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_CONTAINER}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: |
        define( 'RELOCATE', true );
      VIRTUAL_HOST: ${HOSTS}
      VIRTUAL_PORT: ${PORT}
    volumes:
      - ./wp_data:/var/www/html
      - ./assets/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./assets/error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini

  db:
    image: mysql:5.7
    container_name: ${DB_CONTAINER}
    restart: always
    ports: 
          - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./assets/mysql/dump:/docker-entrypoint-initdb.d
      - ./assets/mysql/data:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  wp_data:
  mysql:
