version: '3'

services:
  wordpress:
    container_name: ${WORDPRESS_CONTAINER}
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_CONTAINER}_db"
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: 'false'
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://${HOSTS}' );
        define( 'WP_SITEURL', 'http://${HOSTS}' );
        define( 'WP_CACHE', true);
        define( 'RELOCATE', true );
      VIRTUAL_HOST: ${HOSTS}
      VIRTUAL_PORT: ${PORT_80}
    volumes:
      - ./wp_data:/var/www/html
      - ./assets/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./assets/error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini

  db:
    image: mysql:5.7
    container_name: "${WORDPRESS_CONTAINER}_db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./assets/mysql/dump:/docker-entrypoint-initdb.d
      - ./assets/mysql/data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: "${WORDPRESS_CONTAINER}_mailhog"
    ports:
      - ${MAILHOG_1025}:1025
      - ${MAILHOG_8025}:8025

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  wp_data:
  mysql: